


TOOL_ICON = ":material/construction:"
RESOURCE_ICON = ":material/docs:"
PROMPT_ICON = ":material/chat:"
INPUT_ICON = ":material/place_item:"
OUTPUT_ICON = ":material/publish:"
INFO_ICON = ":material/info:"
ANNOTATION_ICON = ":material/book:"
ANALYSIS_ICON = ":material/search_insights:"
LIGHTBULB_ICON = ":material/lightbulb:"
GAPS_ICON = ":material/rule:"
SERVER_ICON = ":material/lan:"
HOME_ICON = ":material/home:"
CROSS_ICON = ":material/close:"
CHECK_ICON = ":material/check:"
PLAY_ICON = ":material/directions_run:"
PRIORITY_ICON = ":material/priority:"
DELETE_ICON = ":material/delete:"
TEST_SERVER_ICON = ":material/arrow_right:"
EXPLORE_ICON = ":material/discover_tune:"
LLM_ICON = ":material/wand_stars:"
QUESTION_ICON = ":material/help_center:"
PLUGIN_ICON = ":material/power:"
SELECT_ICON = ":material/select_check_box:"
EXECUTE_ICON = ":material/slideshow:"
TEST_ICON = ":material/experiment:"
DOCS_ICON = ":material/menu_book:"
ADD_ICON = ":material/add_box:"
GENERATE_ICON = ":material/autoplay:"
DOWNLOAD_ICON = ":material/download:"

TROUBLESHOOT_ICON = ":material/troubleshoot:"
WARNING_ICON = ":material/emergency_home:"
ERROR_ICON = ":material/dangerous:"
SUCCESS_ICON = ":material/priority:"
