


TOOL_ICON = ":material/construction:"
RESOURCE_ICON = ":material/docs:"
PROMPT_ICON = ":material/chat:"
INPUT_ICON = ":material/place_item:"
OUTPUT_ICON = ":material/publish:"
INFO_ICON = ":material/info:"
ANNOTATION_ICON = ":material/book:"
ANALYSIS_ICON = ":material/search_insights:"
LIGHTBULB_ICON = ":material/lightbulb:"
GAPS_ICON = ":material/rule:"
SERVER_ICON = ":material/lan:"
HOME_ICON = ":material/home:"
CROSS_ICON = ":material/close:"
CHECK_ICON = ":material/check:"
PLAY_ICON = ":material/directions_run:"
PRIORITY_ICON = ":material/priority:"
DELETE_ICON = ":material/delete:"
TEST_ICON = ":material/arrow_right:"

TROUBLESHOOT_ICON = ":material/troubleshoot:"
WARNING_ICON = ":material/emergency_home:"
ERROR_ICON = ":material/dangerous:"
SUCCESS_ICON = ":material/priority:"
