[server]
enableStaticServing=true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/Poppins-Regular.ttf"

[[theme.fontFaces]]
family = "Poppins-bold"
url = "app/static/Poppins-Bold.ttf"

[[theme.fontFaces]]
family = "Roboto"
url = "app/static/Roboto-VariableFont_wdth,wght.ttf"

[[theme.fontFaces]]
family = "Work Sans"
url = "app/static/WorkSans-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
base = "light"
primaryColor = "#D69400"
#backgroundColor = "#EAEAED"
#secondaryBackgroundColor = "black"
#codeBackgroundColor = "black"
#textColor = "#ffffff"
#linkColor = "#0070C0"
#borderColor = "#FFB81C"
showWidgetBorder = true
baseRadius = "medium"
buttonRadius = "medium"

dataframeBorderColor = "#FFD77D"
#dataframeHeaderBackgroundColor = "#FFF3D9"

#showSidebarBorder = true

font = "Work Sans"
#baseFontSize = 15

codeFont = "RobotoMono"
codeFontSize = ".75rem"
#codeBackgroundColor = "#ecebe4"

headingFont = "Poppins-bold"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]

[theme.sidebar]
#backgroundColor = "#121212"
backgroundColor = "#353535"
#secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#353535"
borderColor = "#FFB81C"
#font = "SpaceGrotesk"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]



[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]
showSidebarNavigation=true
toolbarMode = "minimal"
